module.exports = {
    Introduccion: [
        {
            type: "autogenerated",
            dirName: "introduccion",
        },
/*         {
            type: "link",
            label: "Clases de consulta",
            href: "https://classroom.google.com/u/0/c/NTQ1MTg2NjM5NDBa/m/Mzk2Njk5NDA4Mzg1/details",
        }, */
        {
            type: "link",
            label: "Normas académicas y administrativas",
            href: "http://sistemas-utnfra.com.ar/Reglamento.pdf",
        },
    ],
    Clases: [
        "clases/programa",
        "clases/referencias",
        {
            type: "category",
            label: "Introducción a .NET y C#",
            collapsed: true,
            items: [
                {
                    type: "autogenerated",
                    dirName: "clases/01-introduccion",
                },
            ],
        },
        {
            type: "category",
            label: "Clases y métodos estáticos",
            collapsed: true,
            items: [
                {
                    type: "autogenerated",
                    dirName: "clases/02-estaticos",
                },
            ],
        },
        {
            type: "category",
            label: "Programación orientada a objetos",
            collapsed: true,
            items: [
                {
                    type: "autogenerated",
                    dirName: "clases/03-objetos",
                },
            ],
        },
        {
            type: "category",
            label: "Sobrecarga",
            collapsed: true,
            items: [
                {
                    type: "autogenerated",
                    dirName: "clases/04-sobrecarga",
                },
            ],
        },
        {
            type: "category",
            label: "Windows Forms",
            collapsed: true,
            items: [
                {
                    type: "autogenerated",
                    dirName: "clases/05-forms",
                },
            ],
        },
        {
            type: "category",
            label: "Colecciones",
            collapsed: true,
            items: [
                {
                    type: "autogenerated",
                    dirName: "clases/06-colecciones",
                },
            ],
        },
        {
            type: "category",
            label: "Encapsulamiento",
            collapsed: true,
            items: [
                {
                    type: "autogenerated",
                    dirName: "clases/07-encapsulamiento",
                },
            ],
        },
        {
            type: "category",
            label: "Herencia",
            collapsed: true,
            items: [
                {
                    type: "autogenerated",
                    dirName: "clases/08-herencia",
                },
            ],
        },
        {
            type: "category",
            label: "Polimorfismo",
            collapsed: true,
            items: [
                {
                    type: "autogenerated",
                    dirName: "clases/09-polimorfismo",
                },
            ],
        },
        {
            type: "category",
            label: "Excepciones",
            collapsed: true,
            items: [
                {
                    type: "autogenerated",
                    dirName: "clases/10-excepciones",
                },
            ],
        },
        {
            type: "category",
            label: "Pruebas unitarias",
            collapsed: true,
            items: [
                {
                    type: "autogenerated",
                    dirName: "clases/11-testing",
                },
            ],
        },
        {
            type: "category",
            label: "Tipos genéricos",
            collapsed: true,
            items: [
                {
                    type: "autogenerated",
                    dirName: "clases/12-generics",
                },
            ],
        },
        {
            type: "category",
            label: "Interfaces",
            collapsed: true,
            items: [
                {
                    type: "autogenerated",
                    dirName: "clases/13-interfaces",
                },
            ],
        },
        {
            type: "category",
            label: "Archivos",
            collapsed: true,
            items: [
                {
                    type: "autogenerated",
                    dirName: "clases/14-archivos",
                },
            ],
        },
        {
            type: "category",
            label: "Serialización",
            collapsed: true,
            items: [
                {
                    type: "autogenerated",
                    dirName: "clases/15-serializacion",
                },
            ],
        },
        {
            type: "category",
            label: "Introducción a SQL",
            collapsed: true,
            items: [
                {
                    type: "autogenerated",
                    dirName: "clases/16-sql",
                },
            ],
        },
        {
            type: "category",
            label: "Conexión a bases de datos",
            collapsed: true,
            items: [
                {
                    type: "autogenerated",
                    dirName: "clases/17-databases",
                },
            ],
        },
        {
            type: "category",
            label: "Delegados y expresiones lambda",
            collapsed: true,
            items: [
                {
                    type: "autogenerated",
                    dirName: "clases/18-delegados",
                },
            ],
        },
        {
            type: "category",
            label: "Programación multi-hilo y concurrencia",
            collapsed: true,
            items: [
                {
                    type: "autogenerated",
                    dirName: "clases/19-concurrencia",
                },
            ],
        },
        {
            type: "category",
            label: "Eventos",
            collapsed: true,
            items: [
                {
                    type: "autogenerated",
                    dirName: "clases/20-eventos",
                },
            ],
        },
        {
            type: "category",
            label: "Métodos de extensión",
            collapsed: true,
            items: [
                {
                    type: "autogenerated",
                    dirName: "clases/21-otros",
                },
            ],
        },
    ],
    Evaluaciones: [
        "evaluaciones/indice",
        {
            type: "category",
            label: "Trabajos prácticos",
            collapsed: true,
            items: [
                {
                    type: "autogenerated",
                    dirName: "evaluaciones/trabajos-practicos",
                }
            ],
        },
        {
            type: "category",
            label: "Parciales",
            collapsed: true,
            items: [
                {
                    type: "autogenerated",
                    dirName: "evaluaciones/parciales",
                },
            ],
        },
        {
            type: "category",
            label: "Modelos de parcial",
            collapsed: true,
            items: [
                {
                    type: "category",
                    label: "Programación II",
                    collapsed: true,
                    items: [
                        {
                            type: "link",
                            label: "Auto-evaluación - Primer Parcial",
                            href: "https://forms.gle/WkHFoMhjKQQ5jQhR6",
                        },
                        {
                            type: "link",
                            label: "Auto-evaluación - Segundo Parcial",
                            href: "https://forms.gle/PzWFzqM2qhSYvENi6",
                        },
                    ],
                },
                {
                    type: "category",
                    label: "Laboratorio de Computación II",
                    collapsed: true,
                    items: [
                        {
                            type: "category",
                            label: "Primer parcial",
                            collapsed: true,
                            items: [
                                {
                                    type: "autogenerated",
                                    dirName:
                                        "evaluaciones/modelos/laboratorio/primer-parcial",
                                },
                            ],
                        },
                        {
                            type: "category",
                            label: "Segundo parcial",
                            collapsed: true,
                            items: [
                                {
                                    type: "autogenerated",
                                    dirName:
                                        "evaluaciones/modelos/laboratorio/segundo-parcial",
                                },
                            ],
                        },
                        {
                            type: "link",
                            label: "Más modelos de parcial",
                            href: "https://classroom.google.com/u/0/c/NTQ1MTg2NjM5NDBa/m/NTUxNzc4MDA3OTZa/details",
                        },
                    ],
                },
            ],
        },
    ],
};
